name: intercom_example
description: Demonstrates how to use the intercom_flutter plugin.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  intercom_flutter:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.10.0 <3.0.0'