group 'io.maido.intercom'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.2.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
      classpath("com.android.tools.build:gradle:8.13.0")
      classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

def agpMajor = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION.tokenize('.')[0] as int
def builtInKotlin = agpMajor >= 9 &&
    project.findProperty('android.builtInKotlin')?.toString() != 'false'
if (!builtInKotlin) {
    apply plugin: 'kotlin-android'
}

android {
    compileSdk 36
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdk 23
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    if (project.android.hasProperty('namespace')) {
        namespace 'io.maido.intercom'
    }
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'io.intercom.android:intercom-sdk:18.9.3'
    implementation 'io.intercom.android:intercom-sdk-ui:18.9.3'
    implementation 'com.google.firebase:firebase-messaging:25.0.1'
}
